name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci

      - name: Build type definitions
        run: npm run build
        
      - name: Type check
        run: npm run check:type
        
      - name: Lint check
        run: npm run check:lint

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run unit tests
        run: npm run test:unit

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run integration tests
        run: npm run test:integration

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      
      - name: Run e2e tests - RabbitMQ
        run: |
          npm run e2e:setup
          echo "Waiting for services to start..."
          sleep 15
          if ! npm run test:e2e:rabbitmq; then
            npm run e2e:logs:rabbitmq
            npm run e2e:clean
            exit 1
          fi
          npm run e2e:clean
      
      - name: Run e2e tests - SQS
        run: |
          npm run e2e:setup
          echo "Waiting for services to start..."
          sleep 15
          if ! npm run test:e2e:sqs; then
            npm run e2e:logs:sqs
            npm run e2e:clean
            exit 1
          fi
          npm run e2e:clean 